---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-telegram
  namespace: monitoring
spec:
  encryptedData:
    bot-token: AgAksFOvCJASGNHe3UPV0tz7kZ3BE9OtSwCyKuOneWtGRGOn23qTGA8DrU8XRW/elaYeMURcdW4NFeavQeGJ4/Ibp9ukyjRX3E0auNQSzZE4Goblu3hOnF3s+QV3Juk0CMWNTBUYFu9w3JmOv15u3Y4Yb49ttqTYGfiCCyOU2Ry/Og4Lakk5hAjyizmW4F/E5APJrLddXYlYsZ3nkTktcPQuYdodOb1RopzbpBQefBS37WB5owZM8HfQj+S3jp67Tvncecs7+l49N00OlhFXWvfJpX3vHFmdWKgTlg3xgvAJCh5CHp0qxAhrOJDXST2hxo1W3v4P9wwi91uKFbmXdBVxbO8C7ERfM3yIOXNOCPT0SJ7uBq8BRhiD30ZVxmhqASgX5UjVM3QZYTvB5sFY53aZTIzm4Uce5ZrNlE85Gb0e9zan+2NWN+VLdFCEfXrvAV6XMzd/VBhZezJGHNzrcwahi/L5PHOItxCHe/fuLtCoMyzv3zeEW1xy3KQomQDLNKALXmm4L7Xe9cGhjyaFniKilHpu8B/TU/qzyifhZr2OPxRv3taxEwuoFeGDJjwG78ObVbLGfG26A3OPijs3dYLrBeLHzPhx9d5hO0aJcVHpzuZkCHU0vcPMn562bKzl2zk83uYwFFM8qWmFfIc/+DZ78j6HIKuyPsVVWQaT7oVTY16AWDuOOPVuA3TZmQnLK1f9TSSmUkZeixJyZ0GJGHD3SZCm1FoQulBB8jPYuIAzwvqCXkyE0acrme7Uubl8
  template:
    metadata:
      name: alertmanager-telegram
      namespace: monitoring
