---
- name: Validate Kubernetes nodes
  ansible.builtin.include_tasks: nodes.yml

- name: Validate Kubernetes API
  ansible.builtin.include_tasks: api.yml

- name: Validate Cilium
  ansible.builtin.include_tasks: cilium.yml

- name: Validate Gateway API
  ansible.builtin.include_tasks: gateway.yml

- name: Validate HTTPRoutes
  ansible.builtin.include_tasks: httproute.yml

- name: Validate Prometheus
  ansible.builtin.include_tasks: prometheus.yml

- name: Validate etcd backup
  ansible.builtin.include_tasks: etcd_backup.yml

- name: Validate NFS StorageClass
  ansible.builtin.include_tasks: storage.yml

- name: Validate Argo CD components
  ansible.builtin.include_tasks: argocd.yml

- name: Validate Argo CD Applications
  ansible.builtin.include_tasks: argocd_apps.yml

- name: Validate monitoring components
  ansible.builtin.include_tasks: monitoring.yml

- name: Validate end-to-end platform connectivity
  ansible.builtin.include_tasks: end_to_end.yml
