---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: telegram
  namespace: monitoring
spec:
  route:
    receiver: telegram
    matchers:
      - name: severity
        matchType: "="
        value: critical
    groupBy:
      - alertname
      - namespace
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h

  receivers:
    - name: telegram
      telegramConfigs:
        - botToken:
            name: alertmanager-telegram
            key: bot-token
          chatID: 8573958510
          sendResolved: true
          parseMode: HTML
