---
# =========================================================
# Cilium
# =========================================================

- name: Add Cilium Helm repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/
  become: false

- name: Download standard Gateway API CRDs
  ansible.builtin.get_url:
    url: https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.6.1/standard-install.yaml
    dest: /tmp/gateway-api-standard-v1.6.1.yaml
    mode: "0644"
    checksum: sha256:24d931f22abd8e40c973264319ead7cfa09d0fb7716b7ab1ee2ff174cb063a73

- name: Install standard Gateway API CRDs
  kubernetes.core.k8s:
    state: present
    apply: true
    server_side_apply:
      field_manager: ansible
    src: /tmp/gateway-api-standard-v1.6.1.yaml
    kubeconfig: "{{ kubeconfig_path }}"

- name: Install Cilium
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    release_namespace: kube-system
    create_namespace: false
    chart_version: "{{ cilium_version }}"
    state: present
    kubeconfig: "{{ kubeconfig_path }}"
    values:
      ipam:
        mode: cluster-pool
        operator:
          clusterPoolIPv4PodCIDRList:
            - "{{ pod_cidr }}"
      gatewayAPI:
        enabled: true
      kubeProxyReplacement: true
      l2announcements:
        enabled: true
      rollOutCiliumPods: true
  register: cilium_helm

- name: Restart Cilium Operator after Cilium configuration change  # noqa no-changed-when
  ansible.builtin.command:
    cmd: kubectl -n kube-system rollout restart deployment/cilium-operator
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  when:
    - cilium_helm.changed
    - not ansible_check_mode

- name: Wait for Cilium Operator rollout
  ansible.builtin.command:
    cmd: kubectl -n kube-system rollout status deployment/cilium-operator --timeout=180s
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  changed_when: false
  when:
    - cilium_helm.changed
    - not ansible_check_mode
