---
# =========================================================
# Cilium
# =========================================================

- name: Add Cilium Helm repository
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/
  become: false

- name: Download standard Gateway API CRDs
  ansible.builtin.get_url:
    url: https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.6.1/standard-install.yaml
    dest: /tmp/gateway-api-standard-v1.6.1.yaml
    mode: "0644"
    checksum: sha256:24d931f22abd8e40c973264319ead7cfa09d0fb7716b7ab1ee2ff174cb063a73

- name: Install standard Gateway API CRDs
  kubernetes.core.k8s:
    state: present
    apply: true
    server_side_apply:
      field_manager: ansible
    src: /tmp/gateway-api-standard-v1.6.1.yaml
    kubeconfig: /home/ubuntu/.kube/config

- name: Install Cilium
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    release_namespace: kube-system
    create_namespace: false
    chart_version: "{{ cilium_version }}"
    state: present
    kubeconfig: /home/ubuntu/.kube/config
    values:
      ipam:
        mode: cluster-pool
        operator:
          clusterPoolIPv4PodCIDRList:
            - "{{ pod_cidr }}"
      gatewayAPI:
        enabled: true
