---
# =========================================================
# etcd backup configuration
# =========================================================

etcd_version: "3.6.5"

etcd_backup_local_dir: "/var/backups/etcd"

etcd_backup_nfs_server: "192.168.1.27"
etcd_backup_nfs_export: "/srv/nfs/kubernetes"
etcd_backup_nfs_mount: "/mnt/etcd-backup"

etcd_backup_nfs_subdir: "etcd-backup/snapshots"

etcd_backup_retention_days: 7

# =========================================================
# etcd DR restore configuration
# =========================================================

etcd_restore_dir: "/var/lib/etcd-restore"
etcd_restore_client_port: 12379
etcd_restore_peer_port: 12380
