---
# =========================================================
# Additional Control Plane
# =========================================================

- name: Check whether control plane has already joined
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_control_plane_join_control_plane_joined


# =========================================================
# Upload control-plane certificates
# =========================================================

- name: Upload control-plane certificates
  ansible.builtin.command:
    cmd: kubeadm init phase upload-certs --upload-certs
  delegate_to: "{{ groups['control_plane'][0] }}"
  run_once: true
  register: k8s_control_plane_join_certificate_upload
  changed_when: false
  when:
    - inventory_hostname != groups['control_plane'][0]
    - not k8s_control_plane_join_control_plane_joined.stat.exists


# =========================================================
# Extract certificate key
# =========================================================

- name: Extract control-plane certificate key
  ansible.builtin.set_fact:
    k8s_control_plane_join_kubeadm_certificate_key: >-
      {{
        k8s_control_plane_join_certificate_upload.stdout_lines
        | select('match', '^[a-f0-9]{64}$')
        | list
        | last
      }}
  when:
    - inventory_hostname != groups['control_plane'][0]
    - not k8s_control_plane_join_control_plane_joined.stat.exists


# =========================================================
# Generate bootstrap token
# =========================================================

- name: Generate control-plane join command
  ansible.builtin.command:
    cmd: kubeadm token create --print-join-command
  delegate_to: "{{ groups['control_plane'][0] }}"
  run_once: true
  register: k8s_control_plane_join_kubeadm_join_command
  changed_when: false
  when:
    - inventory_hostname != groups['control_plane'][0]
    - not k8s_control_plane_join_control_plane_joined.stat.exists


# =========================================================
# Join additional control plane
# =========================================================

- name: Join additional control plane  # noqa no-changed-when
  ansible.builtin.command:
    cmd: >-
      {{ k8s_control_plane_join_kubeadm_join_command.stdout }}
      --control-plane
      --certificate-key {{ k8s_control_plane_join_kubeadm_certificate_key }}
  when:
    - inventory_hostname != groups['control_plane'][0]
    - not k8s_control_plane_join_control_plane_joined.stat.exists
