---
# =========================================================
# Kubernetes Load Balancers
# =========================================================

- name: Configure Kubernetes Load Balancers
  hosts: load_balancer
  become: true
  roles:
    - load_balancer


# =========================================================
# Kubernetes common configuration
# =========================================================

- name: Configure Kubernetes nodes
  hosts: k8s
  become: true
  roles:
    - k8s_common


# =========================================================
# Bootstrap first control plane
# =========================================================

- name: Bootstrap first control plane
  hosts: control_plane[0]
  become: true
  roles:
    - k8s_control_plane


# =========================================================
# Join additional control planes
# =========================================================

- name: Join additional control planes
  hosts: control_plane
  serial: 1
  become: true
  roles:
    - k8s_control_plane_join


# =========================================================
# Configure control-plane metrics
# =========================================================

- name: Configure control-plane metrics
  hosts: control_plane
  serial: 1
  become: true
  roles:
    - k8s_control_plane_metrics


# =========================================================
# Install Helm
# =========================================================

- name: Install Helm
  hosts: control_plane[0]
  become: true
  roles:
    - helm


# =========================================================
# Install Cilium
# =========================================================

- name: Install Cilium
  hosts: control_plane[0]
  become: false
  roles:
    - cilium


# =========================================================
# Join Kubernetes workers
# =========================================================

- name: Join Kubernetes workers
  hosts: workers
  serial: 1
  become: true
  roles:
    - k8s_worker


# =========================================================
# NFS Server
# =========================================================

- name: Configure NFS server
  hosts: nfs
  become: true
  roles:
    - nfs_server


# =========================================================
# NFS CSI
# =========================================================

- name: Configure NFS CSI
  hosts: control_plane[0]
  become: false
  roles:
    - nfs_csi


# =========================================================
# Install Argo CD
# =========================================================

- name: Install Argo CD
  hosts: control_plane[0]
  become: false
  roles:
    - argocd


# =========================================================
# Bootstrap GitOps
# =========================================================

- name: Bootstrap GitOps
  hosts: control_plane[0]
  become: false
  roles:
    - argocd_bootstrap
