all:
  children:

    k8s:
      children:

        control_plane:
          hosts:
            k8s-cp01:
              ansible_host: 192.168.1.20

            k8s-cp02:
              ansible_host: 192.168.1.23

            k8s-cp03:
              ansible_host: 192.168.1.24

        workers:
          hosts:
            k8s-worker01:
              ansible_host: 192.168.1.21

            k8s-worker02:
              ansible_host: 192.168.1.22

      vars:
        ansible_user: ubuntu

load_balancer:
  hosts:
    k8s-lb01:
      ansible_host: 192.168.1.25
      keepalived_state: MASTER
      keepalived_priority: 110
      keepalived_router_id: K8S-LB01

    k8s-lb02:
      ansible_host: 192.168.1.26
      keepalived_state: BACKUP
      keepalived_priority: 100
      keepalived_router_id: K8S-LB02

  vars:
    ansible_user: ubuntu
