---
- name: Apply Kubernetes sysctl  # noqa no-changed-when
  ansible.builtin.command:
    cmd: sysctl --system

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
