---
# =========================================================
# Argo CD
# =========================================================

- name: Add Argo CD Helm repository
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm
  become: false


- name: Install Argo CD
  kubernetes.core.helm:
    name: argo-cd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    create_namespace: true
    chart_version: "{{ argocd_chart_version }}"
    release_values:
      fullnameOverride: argocd

      configs:
        params:
          server.insecure: "true"

        cm:
          resource.customizations.health.gateway.networking.k8s.io_Gateway: |
            hs = {}
            hs.status = "Progressing"
            hs.message = "Waiting for Gateway to be accepted and programmed"

            if obj.status ~= nil and obj.status.conditions ~= nil then
              accepted = false
              programmed = false

              for _, condition in ipairs(obj.status.conditions) do
                if condition.type == "Accepted" and condition.status == "True" then
                  accepted = true
                end

                if condition.type == "Programmed" and condition.status == "True" then
                  programmed = true
                end
              end

              if accepted and programmed then
                hs.status = "Healthy"
                hs.message = "Gateway is accepted and programmed"
              end
            end

            return hs
    state: present
    kubeconfig: "{{ ansible_facts['user_dir'] }}/.kube/config"


- name: Wait for Argo CD server
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: argocd
    label_selectors:
      - app.kubernetes.io/name=argocd-server
    kubeconfig: "{{ ansible_facts['user_dir'] }}/.kube/config"
  register: argocd_server_pods
  until:
    - argocd_server_pods.resources | length > 0
    - argocd_server_pods.resources
        | selectattr('status.phase', 'equalto', 'Running')
        | list
        | length > 0
  retries: 30
  delay: 10
