---
# =========================================================
# Argo CD
# =========================================================

- name: Add Argo CD Helm repository
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm
  become: false


- name: Install Argo CD
  kubernetes.core.helm:
    name: argo-cd
    chart_ref: argo/argo-cd
    release_namespace: argocd
    create_namespace: true
    chart_version: "{{ argocd_chart_version }}"
    state: present
    kubeconfig: /home/ubuntu/.kube/config


- name: Wait for Argo CD server
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: argocd
    label_selectors:
      - app.kubernetes.io/name=argocd-server
    kubeconfig: /home/ubuntu/.kube/config
  register: argocd_server_pods
  until:
    - argocd_server_pods.resources | length > 0
    - argocd_server_pods.resources
        | selectattr('status.phase', 'equalto', 'Running')
        | list
        | length > 0
  retries: 30
  delay: 10
