---
name: Kubernetes Validate

on:
  pull_request:
    paths:
      - "kubernetes/**"
      - "environments/dev/kubernetes/**"
  workflow_dispatch:

jobs:

  kube:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4


      - name: Install kubeconform
        run: |
          curl -L \
            https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz \
            | tar xz


      - name: Validate manifests
        run: |
          kubernetes_schema='https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/{{.NormalizedKubernetesVersion}}-standalone/{{.ResourceKind}}{{.KindSuffix}}.json'
          crd_schema='https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json'

          find environments/dev/kubernetes kubernetes -type f \
            \( -name '*.yaml' -o -name '*.yml' \) \
            ! -name 'values.yaml' -print0 | \
            xargs -0 ./kubeconform \
              -kubernetes-version 1.34.10 \
              -schema-location "$kubernetes_schema" \
              -schema-location "$crd_schema" \
              -summary
