---
name: Pre Commit

"on":
  pull_request:

jobs:

  precommit:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"


      - name: Install pre-commit
        run: |
          pip install pre-commit


      - name: Run hooks
        run: |
          pre-commit run --all-files
